{{- if not .Values.istio.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal-pathogen.fullname" . }}
  labels:
    {{- include "portal-pathogen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "portal-pathogen.selectorLabels" . | nindent 4 }}
{{- end }}